<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>BroadcastControl</AssemblyName>
    <RootNamespace>BroadcastControl</RootNamespace>
    <Authors>Huafeirong</Authors>
    <Copyright>Copyright © 2026 Huafeirong</Copyright>
    <PackageProjectUrl>https://github.com/huarongfei/EventControlSystem</PackageProjectUrl>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="SocketIOClient" Version="3.1.1" />
  </ItemGroup>
</Project>
